---
apiVersion: v1
kind: Namespace
metadata:
  name: pganalyze-collector-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: pganalyze-collector-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controller
  namespace: pganalyze-collector-controller
rules:
- apiGroups: [""]
  resources:
  - deployments
  - pods
  verbs: ["get", "watch", "list", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller
  namespace: pganalyze-collector-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manage-deployments
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: pganalyze-collector-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: pganalyze-collector-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pganalyze-collector-controller
  template:
    metadata:
      labels:
        app: pganalyze-collector-controller
    spec:
      containers:
      - name: controller
        image: ghcr.io/vlj91/pganalyze-collector-controller:sha-30442cd
        imagePullPolicy: Always
      serviceAccountName: controller
